/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './index.html',
    './impressum.html',
    './datenschutz.html',
    './*.js',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary-fixed': '#dbe1ff',
        'tertiary-container': '#90001c',
        'secondary': '#495d92',
        'on-secondary': '#ffffff',
        'tertiary': '#660011',
        'surface': '#f9f9f9',
        'inverse-surface': '#2f3131',
        'secondary-fixed-dim': '#b2c5ff',
        'surface-tint': '#2d58bf',
        'on-surface-variant': '#434653',
        'tertiary-fixed': '#ffdad8',
        'error': '#ba1a1a',
        'surface-container-lowest': '#ffffff',
        'inverse-on-surface': '#f1f1f1',
        'outline': '#747684',
        'primary-fixed-dim': '#b4c5ff',
        'on-primary-fixed': '#00174b',
        'on-error': '#ffffff',
        'surface-container-low': '#f3f3f3',
        'secondary-container': '#afc2fe',
        'background': '#f9f9f9',
        'surface-variant': '#e2e2e2',
        'on-background': '#1a1c1c',
        'outline-variant': '#c4c6d5',
        'on-error-container': '#93000a',
        'primary': '#002975',
        'on-tertiary-fixed': '#410007',
        'surface-container': '#eeeeee',
        'on-tertiary': '#ffffff',
        'inverse-primary': '#b4c5ff',
        'secondary-fixed': '#dae2ff',
        'on-secondary-fixed-variant': '#314578',
        'primary-container': '#003da5',
        'on-tertiary-container': '#ff9694',
        'on-primary-container': '#98b1ff',
        'on-primary-fixed-variant': '#033ea6',
        'tertiary-fixed-dim': '#ffb3b1',
        'on-surface': '#1a1c1c',
        'error-container': '#ffdad6',
        'surface-container-high': '#e8e8e8',
        'on-primary': '#ffffff',
        'on-secondary-fixed': '#001848',
        'surface-bright': '#f9f9f9',
        'on-secondary-container': '#3b4f83',
        'surface-container-highest': '#e2e2e2',
        'surface-dim': '#dadada',
        'on-tertiary-fixed-variant': '#92001c',
      },
      borderRadius: {
        DEFAULT: '0px',
        lg: '0px',
        xl: '0px',
        full: '0px',
      },
      fontFamily: {
        headline: ["'Playfair Display'", 'Georgia', 'serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
};
